export const GET_INTENT_LIST_INIT = "GET_INTENT_LIST_INIT";
export const GET_INTENT_LIST_SUCCESS = "GET_INTENT_LIST_SUCCESS";
export const GET_INTENT_LIST_FAIL = "GET_INTENT_LIST_FAIL";

export const GET_INTENT_DETAIL_INIT = "GET_INTENT_DETAIL_INIT";
export const GET_INTENT_DETAIL_SUCCESS = "GET_INTENT_DETAIL_SUCCESS";
export const GET_INTENT_DETAIL_FAIL = "GET_INTENT_DETAIL_FAIL";
